### ISSUE TITLE
Function 'set' thrown warning

### ISSUE THREAD

**Issue by asamek** [fwolf/memcached-client#1]
Function `set` thrown warning: `strlen() expects parameter 1 to be string, array given`.

I noticed that you try to get `strlen` on `mixed` type. https://github.com/fwolf/memcached-client/blob/master/memcached.php#L392

**Comment by fwolf** [comment]
Yes I got it.

I checked PHP manual about `Memcached::set()`, seems the parameter `$value` can accept almost any type, and will be serialized before storage, so I may need to serialize it before call of `SocketWrite()`.  Then the `get()` method need adopt to unserialize before return result.

Are you using this class in production environment ? in windows platform ?

**Comment by asamek** [comment]
I'm using this class on testing seerver with Windows 7.
